CREATE TABLE `cat_passport` (
  `passport_id` int(11) NOT NULL AUTO_INCREMENT,
  `passport_content` longtext,
  PRIMARY KEY (`passport_id`)
)

INSERT INTO `sdi_training`.`cat_passport`
(`passport_id`,
`passport_content`)
VALUES
(1,
'{
    "passport_id":"120234-406",
    "age":1,
    "vaccine":[ "D51", "HD3", "FT4"],
    "image":"TDBASGGASDGUSGDUAGBUFBSNVNDJIHBDSAGUBUSAJFNKJNASFKB
 JVAHGSVYGVYSVUHBKHABSFJHBUGASVDYGVYDVUASVDUGASBFJHNASFKJLNAS
 KFJLNSKLGJBJKAFBJHASFJHAFSHBFJKASBKJLNFKCBSJAHBCUSGVCGISAVCU
 HJASBCOHSBCHJASBCUSAVBCUJSAVBCUHSABUHBCHJSBFJBSAFKHBAFHBFJHV
 ASJGDBCJHASVBCJHSAVBCJASBCJHBSAJKCBSAJHBCJKASBVJHSABCJKHSBAC
 JHABSJKCVHAGVDCUYFSDSFGFUWYGBFYBAJSHBFUYAGDIFYGASIBASHBVUIFB
 ASUYFVUISAVBFUISABFUCBUGFBUAGUIFYGBIYSAHFIHASUIFHUIASGBFUIASBF
 UIBFASUI" }');

 INSERT INTO `sdi_training`.`cat_passport`
 (`passport_id`,
 `passport_content`)
 VALUES
 (2,
 '{
     "passport_id":"120234-401",
     "age":11,
     "vaccine":[ "K44", "RD3"],
     "image":"TDBASGGASDGUSGDUAGBUFBSNVNDJIHBDSAGUBUSAJFNKJNASFKB
  JVAHGSVYGVYSVUHBKHABSFJHBUGASVDYGVYDVUASVDUGASBFJHNASFKJLNAS
  KFJLNSKLGJBJKAFBJHASFJHAFSHBFJKASBKJLNFKCBSJAHBCUSGVCGISAVCU
  HJASBCOHSBCHJASBCUSAVBCUJSAVBCUHSABUHBCHJSBFJBSAFKHBAFHBFJHV
  ASJGDBCJHASVBCJHSAVBCJASBCJHBSAJKCBSAJHBCJKASBVJHSABCJKHSBAC
  JHABSJKCVHAGVDCUYFSDSFGFUWYGBFYBAJSHBFUYAGDIFYGASIBASHBVUIFB
  ASUYFVUISAVBFUISABFUCBUGFBUAGUIFYGBIYSAHFIHASUIFHUIASGBFUIASBF
  UIBFASUI" }');